### ISSUE TITLE
the data process of yelp and amazon

### ISSUE THREAD

**Issue by arnold-em** [halaoyy/ARBRE_pytorch#1]
hello，
the yelp and amazon dataset there not have 
would you mind to upload the code
thank you！

**Comment by halaoyy** [comment]
Hello, the yelp and beauty datasets have been uploaded.

**Comment by arnold-em** [comment]
really thank you



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/23/2023 23:16 |
| To | ***@***.***> |
| Cc | hengtong ***@***.***>***@***.***> |
| Subject | Re: [halaoyy/ARBRE_pytorch] the data process of yelp and amazon (Issue #1) |

Hello, the yelp and beauty datasets have been uploaded.
